# Use root/example as user/password credentials
version: "3.8"

services:
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: "db"
    restart: always
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: sys
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  createdb:
    build: createDb/
    depends_on:
        db:
            condition: service_healthy
    healthcheck:
        test: ["CMD", "mysql -u root -p'example' -h db -P3306 -D futbolStats"]
        timeout: 20s
        retries: 10

  populatedb:
    build: populateDb/
    depends_on:
        db:
            condition: service_healthy
